# This only needs to be applied once to create the credentials
# for our CI system
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kubesail
  name: pibox-io-updater
rules:
  - apiGroups: ["apps", "", "networking.k8s.io"]
    resources:
      [
        "deployments",
        "services",
        "ingresses",
        "statefulsets",
        "replicasets",
        "pods",
      ]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps", "", "networking.k8s.io"]
    resources: ["deployments", "services", "ingresses"]
    resourceNames: ["pibox-io", "kubesail-pibox-com"]
    verbs: ["get", "list", "update", "patch", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pibox-io-updater
  namespace: kubesail
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pibox-io-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pibox-io-updater
subjects:
  - kind: ServiceAccount
    name: pibox-io-updater
    namespace: kubesail
